# Etapa 1: build do app
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app

# Copia os arquivos de configuração do Maven
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copia o código e gera o JAR
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: imagem final (mais leve)
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copia o JAR gerado da etapa anterior
COPY --from=builder /app/target/*.jar app.jar

# Expõe a porta padrão do Spring Boot
EXPOSE 8080

# Define o comando de inicialização
ENTRYPOINT ["java", "-jar", "app.jar"]

